//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoconService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeoNode", Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class GeoNode : object
    {
        
        private int CoordSysNumberField;
        
        private double XField;
        
        private double YField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CoordSysNumber
        {
            get
            {
                return this.CoordSysNumberField;
            }
            set
            {
                this.CoordSysNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double X
        {
            get
            {
                return this.XField;
            }
            set
            {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldValue", Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.GeoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.FieldValue[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.FieldCondition[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.FieldCondition))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.EntityRecordSet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.EntityRecord[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.EntityRecord))]
    public partial class FieldValue : object
    {
        
        private string FieldField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldCondition", Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.GeoNode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.FieldValue[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.FieldValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.FieldCondition[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.EntityRecordSet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.EntityRecord[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoconService.EntityRecord))]
    public partial class FieldCondition : object
    {
        
        private string FieldField;
        
        private string OperationField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Operation
        {
            get
            {
                return this.OperationField;
            }
            set
            {
                this.OperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.speerit.nl/CoconServices/CRUD", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityRecordSet", Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class EntityRecordSet : object
    {
        
        private CoconService.ArrayOfString FieldsField;
        
        private CoconService.EntityRecord[] RecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CoconService.ArrayOfString Fields
        {
            get
            {
                return this.FieldsField;
            }
            set
            {
                this.FieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CoconService.EntityRecord[] Records
        {
            get
            {
                return this.RecordsField;
            }
            set
            {
                this.RecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityRecord", Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class EntityRecord : object
    {
        
        private CoconService.FieldValue[] ValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CoconService.FieldValue[] Values
        {
            get
            {
                return this.ValuesField;
            }
            set
            {
                this.ValuesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD", ConfigurationName="CoconService.CRUDSoap")]
    public interface CRUDSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/CRUD/ReserveFiberRoute", ReplyAction="*")]
        System.Threading.Tasks.Task<CoconService.ReserveFiberRouteResponse> ReserveFiberRouteAsync(CoconService.ReserveFiberRouteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/CRUD/CreateRoutingElements", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CoconService.GeoNode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CoconService.FieldValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CoconService.FieldValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CoconService.FieldCondition[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CoconService.FieldCondition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CoconService.ArrayOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CoconService.EntityRecordSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CoconService.EntityRecord[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CoconService.EntityRecord))]
        System.Threading.Tasks.Task<CoconService.CreateRoutingElementsResponse> CreateRoutingElementsAsync(CoconService.CreateRoutingElementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/CRUD/CreateEntity", ReplyAction="*")]
        System.Threading.Tasks.Task<CoconService.CreateEntityResponse> CreateEntityAsync(CoconService.CreateEntityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/CRUD/UpdateEntity", ReplyAction="*")]
        System.Threading.Tasks.Task<CoconService.UpdateEntityResponse> UpdateEntityAsync(CoconService.UpdateEntityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/CRUD/DeleteEntity", ReplyAction="*")]
        System.Threading.Tasks.Task<CoconService.DeleteEntityResponse> DeleteEntityAsync(CoconService.DeleteEntityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/CRUD/ReadEntity", ReplyAction="*")]
        System.Threading.Tasks.Task<CoconService.ReadEntityResponse> ReadEntityAsync(CoconService.ReadEntityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveFiberRouteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveFiberRoute", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.ReserveFiberRouteRequestBody Body;
        
        public ReserveFiberRouteRequest()
        {
        }
        
        public ReserveFiberRouteRequest(CoconService.ReserveFiberRouteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class ReserveFiberRouteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCentralCoconFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string strEnvironment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strCulture;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int intFiberRoutingResultId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int intSelectedSolution;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int intNoOfFibers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string strProject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strInstallCompany;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool blnFutureAsCurrent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool blnRemovalAsCurrent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string strSectionName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string strStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string strContract;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string strServicePriority;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.DateTime dtReserveFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.DateTime dtReserveTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string strRing;
        
        public ReserveFiberRouteRequestBody()
        {
        }
        
        public ReserveFiberRouteRequestBody(
                    string strCentralCoconFolder, 
                    string strEnvironment, 
                    string strUserName, 
                    string strPassword, 
                    string strCulture, 
                    int intFiberRoutingResultId, 
                    int intSelectedSolution, 
                    int intNoOfFibers, 
                    string strProject, 
                    string strInstallCompany, 
                    bool blnFutureAsCurrent, 
                    bool blnRemovalAsCurrent, 
                    string strSectionName, 
                    string strStatus, 
                    string strContract, 
                    string strServicePriority, 
                    System.DateTime dtReserveFrom, 
                    System.DateTime dtReserveTo, 
                    string strRing)
        {
            this.strCentralCoconFolder = strCentralCoconFolder;
            this.strEnvironment = strEnvironment;
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strCulture = strCulture;
            this.intFiberRoutingResultId = intFiberRoutingResultId;
            this.intSelectedSolution = intSelectedSolution;
            this.intNoOfFibers = intNoOfFibers;
            this.strProject = strProject;
            this.strInstallCompany = strInstallCompany;
            this.blnFutureAsCurrent = blnFutureAsCurrent;
            this.blnRemovalAsCurrent = blnRemovalAsCurrent;
            this.strSectionName = strSectionName;
            this.strStatus = strStatus;
            this.strContract = strContract;
            this.strServicePriority = strServicePriority;
            this.dtReserveFrom = dtReserveFrom;
            this.dtReserveTo = dtReserveTo;
            this.strRing = strRing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveFiberRouteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveFiberRouteResponse", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.ReserveFiberRouteResponseBody Body;
        
        public ReserveFiberRouteResponse()
        {
        }
        
        public ReserveFiberRouteResponse(CoconService.ReserveFiberRouteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class ReserveFiberRouteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReserveFiberRouteResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strSectionName;
        
        public ReserveFiberRouteResponseBody()
        {
        }
        
        public ReserveFiberRouteResponseBody(string ReserveFiberRouteResult, string strSectionName)
        {
            this.ReserveFiberRouteResult = ReserveFiberRouteResult;
            this.strSectionName = strSectionName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRoutingElementsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateRoutingElements", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.CreateRoutingElementsRequestBody Body;
        
        public CreateRoutingElementsRequest()
        {
        }
        
        public CreateRoutingElementsRequest(CoconService.CreateRoutingElementsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class CreateRoutingElementsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCentralCoconFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string strEnvironment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strCulture;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int intCrlineId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int intRoutingResultId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int intCustomerContractId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string strCrlineType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strProject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public object strZipcodeA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public object intHouseNrA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public object strSuffixA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public object strBuildingTypeA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public object strZipcodeB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public object intHouseNrB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public object strSuffixB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public object strBuildingTypeB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string strLocationA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string strLocationB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string strFrameA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string strFrameB;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public int intCustomerConnectionTypeA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public int intCustomerConnectionTypeB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string strInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public int intElementsCreated;
        
        public CreateRoutingElementsRequestBody()
        {
        }
        
        public CreateRoutingElementsRequestBody(
                    string strCentralCoconFolder, 
                    string strEnvironment, 
                    string strUserName, 
                    string strPassword, 
                    string strCulture, 
                    int intCrlineId, 
                    int intRoutingResultId, 
                    int intCustomerContractId, 
                    string strCrlineType, 
                    string strProject, 
                    object strZipcodeA, 
                    object intHouseNrA, 
                    object strSuffixA, 
                    object strBuildingTypeA, 
                    object strZipcodeB, 
                    object intHouseNrB, 
                    object strSuffixB, 
                    object strBuildingTypeB, 
                    string strLocationA, 
                    string strLocationB, 
                    string strFrameA, 
                    string strFrameB, 
                    int intCustomerConnectionTypeA, 
                    int intCustomerConnectionTypeB, 
                    string strInfo, 
                    int intElementsCreated)
        {
            this.strCentralCoconFolder = strCentralCoconFolder;
            this.strEnvironment = strEnvironment;
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strCulture = strCulture;
            this.intCrlineId = intCrlineId;
            this.intRoutingResultId = intRoutingResultId;
            this.intCustomerContractId = intCustomerContractId;
            this.strCrlineType = strCrlineType;
            this.strProject = strProject;
            this.strZipcodeA = strZipcodeA;
            this.intHouseNrA = intHouseNrA;
            this.strSuffixA = strSuffixA;
            this.strBuildingTypeA = strBuildingTypeA;
            this.strZipcodeB = strZipcodeB;
            this.intHouseNrB = intHouseNrB;
            this.strSuffixB = strSuffixB;
            this.strBuildingTypeB = strBuildingTypeB;
            this.strLocationA = strLocationA;
            this.strLocationB = strLocationB;
            this.strFrameA = strFrameA;
            this.strFrameB = strFrameB;
            this.intCustomerConnectionTypeA = intCustomerConnectionTypeA;
            this.intCustomerConnectionTypeB = intCustomerConnectionTypeB;
            this.strInfo = strInfo;
            this.intElementsCreated = intElementsCreated;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRoutingElementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateRoutingElementsResponse", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.CreateRoutingElementsResponseBody Body;
        
        public CreateRoutingElementsResponse()
        {
        }
        
        public CreateRoutingElementsResponse(CoconService.CreateRoutingElementsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class CreateRoutingElementsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateRoutingElementsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strLocationA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strLocationB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strFrameA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strFrameB;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int intCustomerConnectionTypeA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int intCustomerConnectionTypeB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int intElementsCreated;
        
        public CreateRoutingElementsResponseBody()
        {
        }
        
        public CreateRoutingElementsResponseBody(string CreateRoutingElementsResult, string strLocationA, string strLocationB, string strFrameA, string strFrameB, int intCustomerConnectionTypeA, int intCustomerConnectionTypeB, string strInfo, int intElementsCreated)
        {
            this.CreateRoutingElementsResult = CreateRoutingElementsResult;
            this.strLocationA = strLocationA;
            this.strLocationB = strLocationB;
            this.strFrameA = strFrameA;
            this.strFrameB = strFrameB;
            this.intCustomerConnectionTypeA = intCustomerConnectionTypeA;
            this.intCustomerConnectionTypeB = intCustomerConnectionTypeB;
            this.strInfo = strInfo;
            this.intElementsCreated = intElementsCreated;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEntityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEntity", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.CreateEntityRequestBody Body;
        
        public CreateEntityRequest()
        {
        }
        
        public CreateEntityRequest(CoconService.CreateEntityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class CreateEntityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCentralCoconFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string strEnvironment;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string strCulture;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string strEntity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CoconService.FieldValue[] objValues;
        
        public CreateEntityRequestBody()
        {
        }
        
        public CreateEntityRequestBody(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, string strEntity, CoconService.FieldValue[] objValues)
        {
            this.strCentralCoconFolder = strCentralCoconFolder;
            this.strEnvironment = strEnvironment;
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strCulture = strCulture;
            this.strEntity = strEntity;
            this.objValues = objValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEntityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEntityResponse", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.CreateEntityResponseBody Body;
        
        public CreateEntityResponse()
        {
        }
        
        public CreateEntityResponse(CoconService.CreateEntityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class CreateEntityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateEntityResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public CoconService.FieldValue[] objValues;
        
        public CreateEntityResponseBody()
        {
        }
        
        public CreateEntityResponseBody(int CreateEntityResult, CoconService.FieldValue[] objValues)
        {
            this.CreateEntityResult = CreateEntityResult;
            this.objValues = objValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEntityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEntity", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.UpdateEntityRequestBody Body;
        
        public UpdateEntityRequest()
        {
        }
        
        public UpdateEntityRequest(CoconService.UpdateEntityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class UpdateEntityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string strCentralCoconFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string strEnvironment;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string strCulture;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string strEntity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CoconService.FieldValue[] objConditions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public CoconService.FieldValue[] objValues;
        
        public UpdateEntityRequestBody()
        {
        }
        
        public UpdateEntityRequestBody(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, string strEntity, CoconService.FieldValue[] objConditions, CoconService.FieldValue[] objValues)
        {
            this.strCentralCoconFolder = strCentralCoconFolder;
            this.strEnvironment = strEnvironment;
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strCulture = strCulture;
            this.strEntity = strEntity;
            this.objConditions = objConditions;
            this.objValues = objValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEntityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEntityResponse", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.UpdateEntityResponseBody Body;
        
        public UpdateEntityResponse()
        {
        }
        
        public UpdateEntityResponse(CoconService.UpdateEntityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class UpdateEntityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateEntityResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public CoconService.FieldValue[] objValues;
        
        public UpdateEntityResponseBody()
        {
        }
        
        public UpdateEntityResponseBody(int UpdateEntityResult, CoconService.FieldValue[] objValues)
        {
            this.UpdateEntityResult = UpdateEntityResult;
            this.objValues = objValues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEntityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEntity", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.DeleteEntityRequestBody Body;
        
        public DeleteEntityRequest()
        {
        }
        
        public DeleteEntityRequest(CoconService.DeleteEntityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class DeleteEntityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string strCentralCoconFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string strEnvironment;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string strCulture;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string strEntity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CoconService.FieldValue[] objConditions;
        
        public DeleteEntityRequestBody()
        {
        }
        
        public DeleteEntityRequestBody(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, string strEntity, CoconService.FieldValue[] objConditions)
        {
            this.strCentralCoconFolder = strCentralCoconFolder;
            this.strEnvironment = strEnvironment;
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strCulture = strCulture;
            this.strEntity = strEntity;
            this.objConditions = objConditions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEntityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEntityResponse", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.DeleteEntityResponseBody Body;
        
        public DeleteEntityResponse()
        {
        }
        
        public DeleteEntityResponse(CoconService.DeleteEntityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class DeleteEntityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteEntityResult;
        
        public DeleteEntityResponseBody()
        {
        }
        
        public DeleteEntityResponseBody(int DeleteEntityResult)
        {
            this.DeleteEntityResult = DeleteEntityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadEntityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadEntity", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.ReadEntityRequestBody Body;
        
        public ReadEntityRequest()
        {
        }
        
        public ReadEntityRequest(CoconService.ReadEntityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class ReadEntityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string strCentralCoconFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string strEnvironment;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string strCulture;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string strContract;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CoconService.FieldCondition[] objConditionValues;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public CoconService.ArrayOfString strFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CoconService.FieldValue[] objFieldOrder;
        
        public ReadEntityRequestBody()
        {
        }
        
        public ReadEntityRequestBody(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, string strContract, CoconService.FieldCondition[] objConditionValues, CoconService.ArrayOfString strFields, CoconService.FieldValue[] objFieldOrder)
        {
            this.strCentralCoconFolder = strCentralCoconFolder;
            this.strEnvironment = strEnvironment;
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strCulture = strCulture;
            this.strContract = strContract;
            this.objConditionValues = objConditionValues;
            this.strFields = strFields;
            this.objFieldOrder = objFieldOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadEntityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadEntityResponse", Namespace="http://www.speerit.nl/CoconServices/CRUD", Order=0)]
        public CoconService.ReadEntityResponseBody Body;
        
        public ReadEntityResponse()
        {
        }
        
        public ReadEntityResponse(CoconService.ReadEntityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/CRUD")]
    public partial class ReadEntityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CoconService.EntityRecordSet ReadEntityResult;
        
        public ReadEntityResponseBody()
        {
        }
        
        public ReadEntityResponseBody(CoconService.EntityRecordSet ReadEntityResult)
        {
            this.ReadEntityResult = ReadEntityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface CRUDSoapChannel : CoconService.CRUDSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class CRUDSoapClient : System.ServiceModel.ClientBase<CoconService.CRUDSoap>, CoconService.CRUDSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CRUDSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CRUDSoapClient.GetBindingForEndpoint(endpointConfiguration), CRUDSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CRUDSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CRUDSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CRUDSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CRUDSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CRUDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CoconService.ReserveFiberRouteResponse> CoconService.CRUDSoap.ReserveFiberRouteAsync(CoconService.ReserveFiberRouteRequest request)
        {
            return base.Channel.ReserveFiberRouteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoconService.ReserveFiberRouteResponse> ReserveFiberRouteAsync(
                    string strCentralCoconFolder, 
                    string strEnvironment, 
                    string strUserName, 
                    string strPassword, 
                    string strCulture, 
                    int intFiberRoutingResultId, 
                    int intSelectedSolution, 
                    int intNoOfFibers, 
                    string strProject, 
                    string strInstallCompany, 
                    bool blnFutureAsCurrent, 
                    bool blnRemovalAsCurrent, 
                    string strSectionName, 
                    string strStatus, 
                    string strContract, 
                    string strServicePriority, 
                    System.DateTime dtReserveFrom, 
                    System.DateTime dtReserveTo, 
                    string strRing)
        {
            CoconService.ReserveFiberRouteRequest inValue = new CoconService.ReserveFiberRouteRequest();
            inValue.Body = new CoconService.ReserveFiberRouteRequestBody();
            inValue.Body.strCentralCoconFolder = strCentralCoconFolder;
            inValue.Body.strEnvironment = strEnvironment;
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strCulture = strCulture;
            inValue.Body.intFiberRoutingResultId = intFiberRoutingResultId;
            inValue.Body.intSelectedSolution = intSelectedSolution;
            inValue.Body.intNoOfFibers = intNoOfFibers;
            inValue.Body.strProject = strProject;
            inValue.Body.strInstallCompany = strInstallCompany;
            inValue.Body.blnFutureAsCurrent = blnFutureAsCurrent;
            inValue.Body.blnRemovalAsCurrent = blnRemovalAsCurrent;
            inValue.Body.strSectionName = strSectionName;
            inValue.Body.strStatus = strStatus;
            inValue.Body.strContract = strContract;
            inValue.Body.strServicePriority = strServicePriority;
            inValue.Body.dtReserveFrom = dtReserveFrom;
            inValue.Body.dtReserveTo = dtReserveTo;
            inValue.Body.strRing = strRing;
            return ((CoconService.CRUDSoap)(this)).ReserveFiberRouteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CoconService.CreateRoutingElementsResponse> CoconService.CRUDSoap.CreateRoutingElementsAsync(CoconService.CreateRoutingElementsRequest request)
        {
            return base.Channel.CreateRoutingElementsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoconService.CreateRoutingElementsResponse> CreateRoutingElementsAsync(
                    string strCentralCoconFolder, 
                    string strEnvironment, 
                    string strUserName, 
                    string strPassword, 
                    string strCulture, 
                    int intCrlineId, 
                    int intRoutingResultId, 
                    int intCustomerContractId, 
                    string strCrlineType, 
                    string strProject, 
                    object strZipcodeA, 
                    object intHouseNrA, 
                    object strSuffixA, 
                    object strBuildingTypeA, 
                    object strZipcodeB, 
                    object intHouseNrB, 
                    object strSuffixB, 
                    object strBuildingTypeB, 
                    string strLocationA, 
                    string strLocationB, 
                    string strFrameA, 
                    string strFrameB, 
                    int intCustomerConnectionTypeA, 
                    int intCustomerConnectionTypeB, 
                    string strInfo, 
                    int intElementsCreated)
        {
            CoconService.CreateRoutingElementsRequest inValue = new CoconService.CreateRoutingElementsRequest();
            inValue.Body = new CoconService.CreateRoutingElementsRequestBody();
            inValue.Body.strCentralCoconFolder = strCentralCoconFolder;
            inValue.Body.strEnvironment = strEnvironment;
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strCulture = strCulture;
            inValue.Body.intCrlineId = intCrlineId;
            inValue.Body.intRoutingResultId = intRoutingResultId;
            inValue.Body.intCustomerContractId = intCustomerContractId;
            inValue.Body.strCrlineType = strCrlineType;
            inValue.Body.strProject = strProject;
            inValue.Body.strZipcodeA = strZipcodeA;
            inValue.Body.intHouseNrA = intHouseNrA;
            inValue.Body.strSuffixA = strSuffixA;
            inValue.Body.strBuildingTypeA = strBuildingTypeA;
            inValue.Body.strZipcodeB = strZipcodeB;
            inValue.Body.intHouseNrB = intHouseNrB;
            inValue.Body.strSuffixB = strSuffixB;
            inValue.Body.strBuildingTypeB = strBuildingTypeB;
            inValue.Body.strLocationA = strLocationA;
            inValue.Body.strLocationB = strLocationB;
            inValue.Body.strFrameA = strFrameA;
            inValue.Body.strFrameB = strFrameB;
            inValue.Body.intCustomerConnectionTypeA = intCustomerConnectionTypeA;
            inValue.Body.intCustomerConnectionTypeB = intCustomerConnectionTypeB;
            inValue.Body.strInfo = strInfo;
            inValue.Body.intElementsCreated = intElementsCreated;
            return ((CoconService.CRUDSoap)(this)).CreateRoutingElementsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CoconService.CreateEntityResponse> CoconService.CRUDSoap.CreateEntityAsync(CoconService.CreateEntityRequest request)
        {
            return base.Channel.CreateEntityAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoconService.CreateEntityResponse> CreateEntityAsync(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, string strEntity, CoconService.FieldValue[] objValues)
        {
            CoconService.CreateEntityRequest inValue = new CoconService.CreateEntityRequest();
            inValue.Body = new CoconService.CreateEntityRequestBody();
            inValue.Body.strCentralCoconFolder = strCentralCoconFolder;
            inValue.Body.strEnvironment = strEnvironment;
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strCulture = strCulture;
            inValue.Body.strEntity = strEntity;
            inValue.Body.objValues = objValues;
            return ((CoconService.CRUDSoap)(this)).CreateEntityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CoconService.UpdateEntityResponse> CoconService.CRUDSoap.UpdateEntityAsync(CoconService.UpdateEntityRequest request)
        {
            return base.Channel.UpdateEntityAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoconService.UpdateEntityResponse> UpdateEntityAsync(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, string strEntity, CoconService.FieldValue[] objConditions, CoconService.FieldValue[] objValues)
        {
            CoconService.UpdateEntityRequest inValue = new CoconService.UpdateEntityRequest();
            inValue.Body = new CoconService.UpdateEntityRequestBody();
            inValue.Body.strCentralCoconFolder = strCentralCoconFolder;
            inValue.Body.strEnvironment = strEnvironment;
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strCulture = strCulture;
            inValue.Body.strEntity = strEntity;
            inValue.Body.objConditions = objConditions;
            inValue.Body.objValues = objValues;
            return ((CoconService.CRUDSoap)(this)).UpdateEntityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CoconService.DeleteEntityResponse> CoconService.CRUDSoap.DeleteEntityAsync(CoconService.DeleteEntityRequest request)
        {
            return base.Channel.DeleteEntityAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoconService.DeleteEntityResponse> DeleteEntityAsync(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, string strEntity, CoconService.FieldValue[] objConditions)
        {
            CoconService.DeleteEntityRequest inValue = new CoconService.DeleteEntityRequest();
            inValue.Body = new CoconService.DeleteEntityRequestBody();
            inValue.Body.strCentralCoconFolder = strCentralCoconFolder;
            inValue.Body.strEnvironment = strEnvironment;
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strCulture = strCulture;
            inValue.Body.strEntity = strEntity;
            inValue.Body.objConditions = objConditions;
            return ((CoconService.CRUDSoap)(this)).DeleteEntityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CoconService.ReadEntityResponse> CoconService.CRUDSoap.ReadEntityAsync(CoconService.ReadEntityRequest request)
        {
            return base.Channel.ReadEntityAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoconService.ReadEntityResponse> ReadEntityAsync(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, string strContract, CoconService.FieldCondition[] objConditionValues, CoconService.ArrayOfString strFields, CoconService.FieldValue[] objFieldOrder)
        {
            CoconService.ReadEntityRequest inValue = new CoconService.ReadEntityRequest();
            inValue.Body = new CoconService.ReadEntityRequestBody();
            inValue.Body.strCentralCoconFolder = strCentralCoconFolder;
            inValue.Body.strEnvironment = strEnvironment;
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strCulture = strCulture;
            inValue.Body.strContract = strContract;
            inValue.Body.objConditionValues = objConditionValues;
            inValue.Body.strFields = strFields;
            inValue.Body.objFieldOrder = objFieldOrder;
            return ((CoconService.CRUDSoap)(this)).ReadEntityAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CRUDSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CRUDSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CRUDSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.speerit.nl/CoconServices/CRUD.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CRUDSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.speerit.nl/CoconServices/CRUD.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CRUDSoap,
            
            CRUDSoap12,
        }
    }
}
