//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTTHManagementV2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FTTHAddressIdentifier", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class FTTHAddressIdentifier : object
    {
        
        private int CoconIdField;
        
        private string ExternalRefField;
        
        private string ZipcodeField;
        
        private int HouseNumberField;
        
        private string HouseNumberExtensionField;
        
        private string RoomField;
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CoconId
        {
            get
            {
                return this.CoconIdField;
            }
            set
            {
                this.CoconIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExternalRef
        {
            get
            {
                return this.ExternalRefField;
            }
            set
            {
                this.ExternalRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Zipcode
        {
            get
            {
                return this.ZipcodeField;
            }
            set
            {
                this.ZipcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int HouseNumber
        {
            get
            {
                return this.HouseNumberField;
            }
            set
            {
                this.HouseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HouseNumberExtension
        {
            get
            {
                return this.HouseNumberExtensionField;
            }
            set
            {
                this.HouseNumberExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Room
        {
            get
            {
                return this.RoomField;
            }
            set
            {
                this.RoomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", ConfigurationName="FTTHManagementV2.FTTHManagementSoap")]
    public interface FTTHManagementSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/FTTHManagement/PutAsBuilt", ReplyAction="*")]
        System.Threading.Tasks.Task<FTTHManagementV2.PutAsBuiltResponse> PutAsBuiltAsync(FTTHManagementV2.PutAsBuiltRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/FTTHManagement/ParseReggefiberProject", ReplyAction="*")]
        System.Threading.Tasks.Task<FTTHManagementV2.ParseReggefiberProjectResponse> ParseReggefiberProjectAsync(FTTHManagementV2.ParseReggefiberProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/FTTHManagement/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<FTTHManagementV2.LoginResponse> LoginAsync(FTTHManagementV2.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/FTTHManagement/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task LogoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/FTTHManagement/ChangeDevicePort", ReplyAction="*")]
        System.Threading.Tasks.Task<FTTHManagementV2.ChangeDevicePortResponse> ChangeDevicePortAsync(FTTHManagementV2.ChangeDevicePortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/FTTHManagement/ChangeDevicePortV2", ReplyAction="*")]
        System.Threading.Tasks.Task<FTTHManagementV2.ChangeDevicePortV2Response> ChangeDevicePortV2Async(FTTHManagementV2.ChangeDevicePortV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/FTTHManagement/GetUnreferencedFTTHAddresses", ReplyAction="*")]
        System.Threading.Tasks.Task<FTTHManagementV2.GetUnreferencedFTTHAddressesResponse> GetUnreferencedFTTHAddressesAsync(FTTHManagementV2.GetUnreferencedFTTHAddressesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/FTTHManagement/ReferenceFTTHAddresses", ReplyAction="*")]
        System.Threading.Tasks.Task<FTTHManagementV2.ReferenceFTTHAddressesResponse> ReferenceFTTHAddressesAsync(FTTHManagementV2.ReferenceFTTHAddressesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.speerit.nl/CoconServices/FTTHManagement/SetFTTHAddressTerminationIds", ReplyAction="*")]
        System.Threading.Tasks.Task<FTTHManagementV2.SetFTTHAddressTerminationIdsResponse> SetFTTHAddressTerminationIdsAsync(FTTHManagementV2.SetFTTHAddressTerminationIdsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutAsBuiltRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutAsBuilt", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.PutAsBuiltRequestBody Body;
        
        public PutAsBuiltRequest()
        {
        }
        
        public PutAsBuiltRequest(FTTHManagementV2.PutAsBuiltRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class PutAsBuiltRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strFilePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] objCompressedBytes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strContractor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strUpdateUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strUpdateReason;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime dtLastWriteTime;
        
        public PutAsBuiltRequestBody()
        {
        }
        
        public PutAsBuiltRequestBody(string strFilePath, byte[] objCompressedBytes, string strContractor, string strUpdateUser, string strUpdateReason, System.DateTime dtLastWriteTime)
        {
            this.strFilePath = strFilePath;
            this.objCompressedBytes = objCompressedBytes;
            this.strContractor = strContractor;
            this.strUpdateUser = strUpdateUser;
            this.strUpdateReason = strUpdateReason;
            this.dtLastWriteTime = dtLastWriteTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutAsBuiltResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutAsBuiltResponse", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.PutAsBuiltResponseBody Body;
        
        public PutAsBuiltResponse()
        {
        }
        
        public PutAsBuiltResponse(FTTHManagementV2.PutAsBuiltResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PutAsBuiltResponseBody
    {
        
        public PutAsBuiltResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParseReggefiberProjectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParseReggefiberProject", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.ParseReggefiberProjectRequestBody Body;
        
        public ParseReggefiberProjectRequest()
        {
        }
        
        public ParseReggefiberProjectRequest(FTTHManagementV2.ParseReggefiberProjectRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class ParseReggefiberProjectRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strProject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPop;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strBuild;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strPhase;
        
        public ParseReggefiberProjectRequestBody()
        {
        }
        
        public ParseReggefiberProjectRequestBody(string strProject, string strPop, string strType, string strBuild, string strPhase)
        {
            this.strProject = strProject;
            this.strPop = strPop;
            this.strType = strType;
            this.strBuild = strBuild;
            this.strPhase = strPhase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParseReggefiberProjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParseReggefiberProjectResponse", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.ParseReggefiberProjectResponseBody Body;
        
        public ParseReggefiberProjectResponse()
        {
        }
        
        public ParseReggefiberProjectResponse(FTTHManagementV2.ParseReggefiberProjectResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class ParseReggefiberProjectResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ParseReggefiberProjectResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPop;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strBuild;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strPhase;
        
        public ParseReggefiberProjectResponseBody()
        {
        }
        
        public ParseReggefiberProjectResponseBody(bool ParseReggefiberProjectResult, string strPop, string strType, string strBuild, string strPhase)
        {
            this.ParseReggefiberProjectResult = ParseReggefiberProjectResult;
            this.strPop = strPop;
            this.strType = strType;
            this.strBuild = strBuild;
            this.strPhase = strPhase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.LoginRequestBody Body;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(FTTHManagementV2.LoginRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class LoginRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCentralCoconFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strEnvironment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strCulture;
        
        public LoginRequestBody()
        {
        }
        
        public LoginRequestBody(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture)
        {
            this.strCentralCoconFolder = strCentralCoconFolder;
            this.strEnvironment = strEnvironment;
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strCulture = strCulture;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.LoginResponseBody Body;
        
        public LoginResponse()
        {
        }
        
        public LoginResponse(FTTHManagementV2.LoginResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoginResponseBody
    {
        
        public LoginResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeDevicePortRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeDevicePort", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.ChangeDevicePortRequestBody Body;
        
        public ChangeDevicePortRequest()
        {
        }
        
        public ChangeDevicePortRequest(FTTHManagementV2.ChangeDevicePortRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class ChangeDevicePortRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strZipcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int intHouseNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strHouseNumberExtension;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strRoom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int intFiber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strDevicePort;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strOrderType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime dtOrderDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strRequestUser;
        
        public ChangeDevicePortRequestBody()
        {
        }
        
        public ChangeDevicePortRequestBody(string strZipcode, int intHouseNumber, string strHouseNumberExtension, string strRoom, int intFiber, string strDevicePort, string strOrderType, string strOrderId, System.DateTime dtOrderDate, string strRequestUser)
        {
            this.strZipcode = strZipcode;
            this.intHouseNumber = intHouseNumber;
            this.strHouseNumberExtension = strHouseNumberExtension;
            this.strRoom = strRoom;
            this.intFiber = intFiber;
            this.strDevicePort = strDevicePort;
            this.strOrderType = strOrderType;
            this.strOrderId = strOrderId;
            this.dtOrderDate = dtOrderDate;
            this.strRequestUser = strRequestUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeDevicePortResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeDevicePortResponse", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.ChangeDevicePortResponseBody Body;
        
        public ChangeDevicePortResponse()
        {
        }
        
        public ChangeDevicePortResponse(FTTHManagementV2.ChangeDevicePortResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChangeDevicePortResponseBody
    {
        
        public ChangeDevicePortResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeDevicePortV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeDevicePortV2", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.ChangeDevicePortV2RequestBody Body;
        
        public ChangeDevicePortV2Request()
        {
        }
        
        public ChangeDevicePortV2Request(FTTHManagementV2.ChangeDevicePortV2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class ChangeDevicePortV2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strZipcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int intHouseNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strHouseNumberExtension;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strRoom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int intFiber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strDevicePort;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strOrderType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime dtOrderDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strRequestUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string strActiveOperator;
        
        public ChangeDevicePortV2RequestBody()
        {
        }
        
        public ChangeDevicePortV2RequestBody(string strZipcode, int intHouseNumber, string strHouseNumberExtension, string strRoom, int intFiber, string strDevicePort, string strOrderType, string strOrderId, System.DateTime dtOrderDate, string strRequestUser, string strActiveOperator)
        {
            this.strZipcode = strZipcode;
            this.intHouseNumber = intHouseNumber;
            this.strHouseNumberExtension = strHouseNumberExtension;
            this.strRoom = strRoom;
            this.intFiber = intFiber;
            this.strDevicePort = strDevicePort;
            this.strOrderType = strOrderType;
            this.strOrderId = strOrderId;
            this.dtOrderDate = dtOrderDate;
            this.strRequestUser = strRequestUser;
            this.strActiveOperator = strActiveOperator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeDevicePortV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeDevicePortV2Response", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.ChangeDevicePortV2ResponseBody Body;
        
        public ChangeDevicePortV2Response()
        {
        }
        
        public ChangeDevicePortV2Response(FTTHManagementV2.ChangeDevicePortV2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChangeDevicePortV2ResponseBody
    {
        
        public ChangeDevicePortV2ResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnreferencedFTTHAddressesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnreferencedFTTHAddresses", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.GetUnreferencedFTTHAddressesRequestBody Body;
        
        public GetUnreferencedFTTHAddressesRequest()
        {
        }
        
        public GetUnreferencedFTTHAddressesRequest(FTTHManagementV2.GetUnreferencedFTTHAddressesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class GetUnreferencedFTTHAddressesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string strCentralCoconFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string strEnvironment;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string strCulture;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int intMaxResults;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string strFlags;
        
        public GetUnreferencedFTTHAddressesRequestBody()
        {
        }
        
        public GetUnreferencedFTTHAddressesRequestBody(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, int intMaxResults, string strFlags)
        {
            this.strCentralCoconFolder = strCentralCoconFolder;
            this.strEnvironment = strEnvironment;
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strCulture = strCulture;
            this.intMaxResults = intMaxResults;
            this.strFlags = strFlags;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnreferencedFTTHAddressesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnreferencedFTTHAddressesResponse", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.GetUnreferencedFTTHAddressesResponseBody Body;
        
        public GetUnreferencedFTTHAddressesResponse()
        {
        }
        
        public GetUnreferencedFTTHAddressesResponse(FTTHManagementV2.GetUnreferencedFTTHAddressesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class GetUnreferencedFTTHAddressesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FTTHManagementV2.FTTHAddressIdentifier[] GetUnreferencedFTTHAddressesResult;
        
        public GetUnreferencedFTTHAddressesResponseBody()
        {
        }
        
        public GetUnreferencedFTTHAddressesResponseBody(FTTHManagementV2.FTTHAddressIdentifier[] GetUnreferencedFTTHAddressesResult)
        {
            this.GetUnreferencedFTTHAddressesResult = GetUnreferencedFTTHAddressesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReferenceFTTHAddressesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReferenceFTTHAddresses", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.ReferenceFTTHAddressesRequestBody Body;
        
        public ReferenceFTTHAddressesRequest()
        {
        }
        
        public ReferenceFTTHAddressesRequest(FTTHManagementV2.ReferenceFTTHAddressesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class ReferenceFTTHAddressesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string strCentralCoconFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string strEnvironment;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string strCulture;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public FTTHManagementV2.FTTHAddressIdentifier[] objAddresses;
        
        public ReferenceFTTHAddressesRequestBody()
        {
        }
        
        public ReferenceFTTHAddressesRequestBody(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, FTTHManagementV2.FTTHAddressIdentifier[] objAddresses)
        {
            this.strCentralCoconFolder = strCentralCoconFolder;
            this.strEnvironment = strEnvironment;
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strCulture = strCulture;
            this.objAddresses = objAddresses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReferenceFTTHAddressesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReferenceFTTHAddressesResponse", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.ReferenceFTTHAddressesResponseBody Body;
        
        public ReferenceFTTHAddressesResponse()
        {
        }
        
        public ReferenceFTTHAddressesResponse(FTTHManagementV2.ReferenceFTTHAddressesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class ReferenceFTTHAddressesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FTTHManagementV2.FTTHAddressIdentifier[] objAddresses;
        
        public ReferenceFTTHAddressesResponseBody()
        {
        }
        
        public ReferenceFTTHAddressesResponseBody(FTTHManagementV2.FTTHAddressIdentifier[] objAddresses)
        {
            this.objAddresses = objAddresses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetFTTHAddressTerminationIdsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetFTTHAddressTerminationIds", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.SetFTTHAddressTerminationIdsRequestBody Body;
        
        public SetFTTHAddressTerminationIdsRequest()
        {
        }
        
        public SetFTTHAddressTerminationIdsRequest(FTTHManagementV2.SetFTTHAddressTerminationIdsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.speerit.nl/CoconServices/FTTHManagement")]
    public partial class SetFTTHAddressTerminationIdsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string strCentralCoconFolder;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string strEnvironment;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string strCulture;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strProject;
        
        public SetFTTHAddressTerminationIdsRequestBody()
        {
        }
        
        public SetFTTHAddressTerminationIdsRequestBody(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, string strProject)
        {
            this.strCentralCoconFolder = strCentralCoconFolder;
            this.strEnvironment = strEnvironment;
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strCulture = strCulture;
            this.strProject = strProject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetFTTHAddressTerminationIdsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetFTTHAddressTerminationIdsResponse", Namespace="http://www.speerit.nl/CoconServices/FTTHManagement", Order=0)]
        public FTTHManagementV2.SetFTTHAddressTerminationIdsResponseBody Body;
        
        public SetFTTHAddressTerminationIdsResponse()
        {
        }
        
        public SetFTTHAddressTerminationIdsResponse(FTTHManagementV2.SetFTTHAddressTerminationIdsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetFTTHAddressTerminationIdsResponseBody
    {
        
        public SetFTTHAddressTerminationIdsResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface FTTHManagementSoapChannel : FTTHManagementV2.FTTHManagementSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class FTTHManagementSoapClient : System.ServiceModel.ClientBase<FTTHManagementV2.FTTHManagementSoap>, FTTHManagementV2.FTTHManagementSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FTTHManagementSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(FTTHManagementSoapClient.GetBindingForEndpoint(endpointConfiguration), FTTHManagementSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FTTHManagementSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FTTHManagementSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FTTHManagementSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FTTHManagementSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FTTHManagementSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FTTHManagementV2.PutAsBuiltResponse> FTTHManagementV2.FTTHManagementSoap.PutAsBuiltAsync(FTTHManagementV2.PutAsBuiltRequest request)
        {
            return base.Channel.PutAsBuiltAsync(request);
        }
        
        public System.Threading.Tasks.Task<FTTHManagementV2.PutAsBuiltResponse> PutAsBuiltAsync(string strFilePath, byte[] objCompressedBytes, string strContractor, string strUpdateUser, string strUpdateReason, System.DateTime dtLastWriteTime)
        {
            FTTHManagementV2.PutAsBuiltRequest inValue = new FTTHManagementV2.PutAsBuiltRequest();
            inValue.Body = new FTTHManagementV2.PutAsBuiltRequestBody();
            inValue.Body.strFilePath = strFilePath;
            inValue.Body.objCompressedBytes = objCompressedBytes;
            inValue.Body.strContractor = strContractor;
            inValue.Body.strUpdateUser = strUpdateUser;
            inValue.Body.strUpdateReason = strUpdateReason;
            inValue.Body.dtLastWriteTime = dtLastWriteTime;
            return ((FTTHManagementV2.FTTHManagementSoap)(this)).PutAsBuiltAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FTTHManagementV2.ParseReggefiberProjectResponse> FTTHManagementV2.FTTHManagementSoap.ParseReggefiberProjectAsync(FTTHManagementV2.ParseReggefiberProjectRequest request)
        {
            return base.Channel.ParseReggefiberProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<FTTHManagementV2.ParseReggefiberProjectResponse> ParseReggefiberProjectAsync(string strProject, string strPop, string strType, string strBuild, string strPhase)
        {
            FTTHManagementV2.ParseReggefiberProjectRequest inValue = new FTTHManagementV2.ParseReggefiberProjectRequest();
            inValue.Body = new FTTHManagementV2.ParseReggefiberProjectRequestBody();
            inValue.Body.strProject = strProject;
            inValue.Body.strPop = strPop;
            inValue.Body.strType = strType;
            inValue.Body.strBuild = strBuild;
            inValue.Body.strPhase = strPhase;
            return ((FTTHManagementV2.FTTHManagementSoap)(this)).ParseReggefiberProjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FTTHManagementV2.LoginResponse> FTTHManagementV2.FTTHManagementSoap.LoginAsync(FTTHManagementV2.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<FTTHManagementV2.LoginResponse> LoginAsync(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture)
        {
            FTTHManagementV2.LoginRequest inValue = new FTTHManagementV2.LoginRequest();
            inValue.Body = new FTTHManagementV2.LoginRequestBody();
            inValue.Body.strCentralCoconFolder = strCentralCoconFolder;
            inValue.Body.strEnvironment = strEnvironment;
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strCulture = strCulture;
            return ((FTTHManagementV2.FTTHManagementSoap)(this)).LoginAsync(inValue);
        }
        
        public System.Threading.Tasks.Task LogoutAsync()
        {
            return base.Channel.LogoutAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FTTHManagementV2.ChangeDevicePortResponse> FTTHManagementV2.FTTHManagementSoap.ChangeDevicePortAsync(FTTHManagementV2.ChangeDevicePortRequest request)
        {
            return base.Channel.ChangeDevicePortAsync(request);
        }
        
        public System.Threading.Tasks.Task<FTTHManagementV2.ChangeDevicePortResponse> ChangeDevicePortAsync(string strZipcode, int intHouseNumber, string strHouseNumberExtension, string strRoom, int intFiber, string strDevicePort, string strOrderType, string strOrderId, System.DateTime dtOrderDate, string strRequestUser)
        {
            FTTHManagementV2.ChangeDevicePortRequest inValue = new FTTHManagementV2.ChangeDevicePortRequest();
            inValue.Body = new FTTHManagementV2.ChangeDevicePortRequestBody();
            inValue.Body.strZipcode = strZipcode;
            inValue.Body.intHouseNumber = intHouseNumber;
            inValue.Body.strHouseNumberExtension = strHouseNumberExtension;
            inValue.Body.strRoom = strRoom;
            inValue.Body.intFiber = intFiber;
            inValue.Body.strDevicePort = strDevicePort;
            inValue.Body.strOrderType = strOrderType;
            inValue.Body.strOrderId = strOrderId;
            inValue.Body.dtOrderDate = dtOrderDate;
            inValue.Body.strRequestUser = strRequestUser;
            return ((FTTHManagementV2.FTTHManagementSoap)(this)).ChangeDevicePortAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FTTHManagementV2.ChangeDevicePortV2Response> FTTHManagementV2.FTTHManagementSoap.ChangeDevicePortV2Async(FTTHManagementV2.ChangeDevicePortV2Request request)
        {
            return base.Channel.ChangeDevicePortV2Async(request);
        }
        
        public System.Threading.Tasks.Task<FTTHManagementV2.ChangeDevicePortV2Response> ChangeDevicePortV2Async(string strZipcode, int intHouseNumber, string strHouseNumberExtension, string strRoom, int intFiber, string strDevicePort, string strOrderType, string strOrderId, System.DateTime dtOrderDate, string strRequestUser, string strActiveOperator)
        {
            FTTHManagementV2.ChangeDevicePortV2Request inValue = new FTTHManagementV2.ChangeDevicePortV2Request();
            inValue.Body = new FTTHManagementV2.ChangeDevicePortV2RequestBody();
            inValue.Body.strZipcode = strZipcode;
            inValue.Body.intHouseNumber = intHouseNumber;
            inValue.Body.strHouseNumberExtension = strHouseNumberExtension;
            inValue.Body.strRoom = strRoom;
            inValue.Body.intFiber = intFiber;
            inValue.Body.strDevicePort = strDevicePort;
            inValue.Body.strOrderType = strOrderType;
            inValue.Body.strOrderId = strOrderId;
            inValue.Body.dtOrderDate = dtOrderDate;
            inValue.Body.strRequestUser = strRequestUser;
            inValue.Body.strActiveOperator = strActiveOperator;
            return ((FTTHManagementV2.FTTHManagementSoap)(this)).ChangeDevicePortV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FTTHManagementV2.GetUnreferencedFTTHAddressesResponse> FTTHManagementV2.FTTHManagementSoap.GetUnreferencedFTTHAddressesAsync(FTTHManagementV2.GetUnreferencedFTTHAddressesRequest request)
        {
            return base.Channel.GetUnreferencedFTTHAddressesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FTTHManagementV2.GetUnreferencedFTTHAddressesResponse> GetUnreferencedFTTHAddressesAsync(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, int intMaxResults, string strFlags)
        {
            FTTHManagementV2.GetUnreferencedFTTHAddressesRequest inValue = new FTTHManagementV2.GetUnreferencedFTTHAddressesRequest();
            inValue.Body = new FTTHManagementV2.GetUnreferencedFTTHAddressesRequestBody();
            inValue.Body.strCentralCoconFolder = strCentralCoconFolder;
            inValue.Body.strEnvironment = strEnvironment;
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strCulture = strCulture;
            inValue.Body.intMaxResults = intMaxResults;
            inValue.Body.strFlags = strFlags;
            return ((FTTHManagementV2.FTTHManagementSoap)(this)).GetUnreferencedFTTHAddressesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FTTHManagementV2.ReferenceFTTHAddressesResponse> FTTHManagementV2.FTTHManagementSoap.ReferenceFTTHAddressesAsync(FTTHManagementV2.ReferenceFTTHAddressesRequest request)
        {
            return base.Channel.ReferenceFTTHAddressesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FTTHManagementV2.ReferenceFTTHAddressesResponse> ReferenceFTTHAddressesAsync(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, FTTHManagementV2.FTTHAddressIdentifier[] objAddresses)
        {
            FTTHManagementV2.ReferenceFTTHAddressesRequest inValue = new FTTHManagementV2.ReferenceFTTHAddressesRequest();
            inValue.Body = new FTTHManagementV2.ReferenceFTTHAddressesRequestBody();
            inValue.Body.strCentralCoconFolder = strCentralCoconFolder;
            inValue.Body.strEnvironment = strEnvironment;
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strCulture = strCulture;
            inValue.Body.objAddresses = objAddresses;
            return ((FTTHManagementV2.FTTHManagementSoap)(this)).ReferenceFTTHAddressesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FTTHManagementV2.SetFTTHAddressTerminationIdsResponse> FTTHManagementV2.FTTHManagementSoap.SetFTTHAddressTerminationIdsAsync(FTTHManagementV2.SetFTTHAddressTerminationIdsRequest request)
        {
            return base.Channel.SetFTTHAddressTerminationIdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FTTHManagementV2.SetFTTHAddressTerminationIdsResponse> SetFTTHAddressTerminationIdsAsync(string strCentralCoconFolder, string strEnvironment, string strUserName, string strPassword, string strCulture, string strProject)
        {
            FTTHManagementV2.SetFTTHAddressTerminationIdsRequest inValue = new FTTHManagementV2.SetFTTHAddressTerminationIdsRequest();
            inValue.Body = new FTTHManagementV2.SetFTTHAddressTerminationIdsRequestBody();
            inValue.Body.strCentralCoconFolder = strCentralCoconFolder;
            inValue.Body.strEnvironment = strEnvironment;
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strCulture = strCulture;
            inValue.Body.strProject = strProject;
            return ((FTTHManagementV2.FTTHManagementSoap)(this)).SetFTTHAddressTerminationIdsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FTTHManagementSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FTTHManagementSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FTTHManagementSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/CoconServices/ftthmanagement.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.FTTHManagementSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/CoconServices/ftthmanagement.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            FTTHManagementSoap,
            
            FTTHManagementSoap12,
        }
    }
}
