//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIsAcService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BcViewResponseBody", Namespace="http://cif.speerit.nl/")]
    public partial class BcViewResponseBody : object
    {
        
        private IIsAcService.BcResultaat[] BcViewResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IIsAcService.BcResultaat[] BcViewResult
        {
            get
            {
                return this.BcViewResultField;
            }
            set
            {
                this.BcViewResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BcResultaat", Namespace="http://cif.speerit.nl/")]
    public partial class BcResultaat : object
    {
        
        private string FoutmeldingField;
        
        private string POSTCODEField;
        
        private string HUISNRField;
        
        private string TOEVOEGINGField;
        
        private string KAMERField;
        
        private string FTU_TYPEField;
        
        private string AFWERKSTATUSField;
        
        private string AREAPOPField;
        
        private string RIJField;
        
        private string KAST_IPField;
        
        private string ODF_IPField;
        
        private string ODFPOSITIE_IPField;
        
        private string KAST_CATVField;
        
        private string ODF_CATVField;
        
        private string ODFPOSITIE_CATVField;
        
        private string PROJECTNRField;
        
        private string BOUWBESTANDSTATUSField;
        
        private string OPLEVERSTATUS_TOEVOEGINGField;
        
        private string APPARATUURPOORT_IPField;
        
        private string APPARATUURPOORT_CATVField;
        
        private string LAST_UPDATED_IPField;
        
        private string LAST_UPDATE_CATVField;
        
        private string REDEN_APP_POORT_IPField;
        
        private string REDEN_APP_POORT_CATVField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string POSTCODE
        {
            get
            {
                return this.POSTCODEField;
            }
            set
            {
                this.POSTCODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HUISNR
        {
            get
            {
                return this.HUISNRField;
            }
            set
            {
                this.HUISNRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TOEVOEGING
        {
            get
            {
                return this.TOEVOEGINGField;
            }
            set
            {
                this.TOEVOEGINGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string KAMER
        {
            get
            {
                return this.KAMERField;
            }
            set
            {
                this.KAMERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FTU_TYPE
        {
            get
            {
                return this.FTU_TYPEField;
            }
            set
            {
                this.FTU_TYPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AFWERKSTATUS
        {
            get
            {
                return this.AFWERKSTATUSField;
            }
            set
            {
                this.AFWERKSTATUSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AREAPOP
        {
            get
            {
                return this.AREAPOPField;
            }
            set
            {
                this.AREAPOPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string RIJ
        {
            get
            {
                return this.RIJField;
            }
            set
            {
                this.RIJField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string KAST_IP
        {
            get
            {
                return this.KAST_IPField;
            }
            set
            {
                this.KAST_IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ODF_IP
        {
            get
            {
                return this.ODF_IPField;
            }
            set
            {
                this.ODF_IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ODFPOSITIE_IP
        {
            get
            {
                return this.ODFPOSITIE_IPField;
            }
            set
            {
                this.ODFPOSITIE_IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string KAST_CATV
        {
            get
            {
                return this.KAST_CATVField;
            }
            set
            {
                this.KAST_CATVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ODF_CATV
        {
            get
            {
                return this.ODF_CATVField;
            }
            set
            {
                this.ODF_CATVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ODFPOSITIE_CATV
        {
            get
            {
                return this.ODFPOSITIE_CATVField;
            }
            set
            {
                this.ODFPOSITIE_CATVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string PROJECTNR
        {
            get
            {
                return this.PROJECTNRField;
            }
            set
            {
                this.PROJECTNRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string BOUWBESTANDSTATUS
        {
            get
            {
                return this.BOUWBESTANDSTATUSField;
            }
            set
            {
                this.BOUWBESTANDSTATUSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string OPLEVERSTATUS_TOEVOEGING
        {
            get
            {
                return this.OPLEVERSTATUS_TOEVOEGINGField;
            }
            set
            {
                this.OPLEVERSTATUS_TOEVOEGINGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string APPARATUURPOORT_IP
        {
            get
            {
                return this.APPARATUURPOORT_IPField;
            }
            set
            {
                this.APPARATUURPOORT_IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string APPARATUURPOORT_CATV
        {
            get
            {
                return this.APPARATUURPOORT_CATVField;
            }
            set
            {
                this.APPARATUURPOORT_CATVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string LAST_UPDATED_IP
        {
            get
            {
                return this.LAST_UPDATED_IPField;
            }
            set
            {
                this.LAST_UPDATED_IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string LAST_UPDATE_CATV
        {
            get
            {
                return this.LAST_UPDATE_CATVField;
            }
            set
            {
                this.LAST_UPDATE_CATVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string REDEN_APP_POORT_IP
        {
            get
            {
                return this.REDEN_APP_POORT_IPField;
            }
            set
            {
                this.REDEN_APP_POORT_IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string REDEN_APP_POORT_CATV
        {
            get
            {
                return this.REDEN_APP_POORT_CATVField;
            }
            set
            {
                this.REDEN_APP_POORT_CATVField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cif.speerit.nl/", ConfigurationName="IIsAcService.IIsacClient")]
    public interface IIsacClient
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cif.speerit.nl/IIsacClient/BcView", ReplyAction="http://cif.speerit.nl/IIsacClient/BcViewResponse")]
        System.Threading.Tasks.Task<IIsAcService.BcViewResponse> BcViewAsync(IIsAcService.BcViewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cif.speerit.nl/IIsacClient/BcViewResponseStream", ReplyAction="http://cif.speerit.nl/IIsacClient/BcViewResponseStreamResponse")]
        System.Threading.Tasks.Task<byte[]> BcViewResponseStreamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cif.speerit.nl/IIsacClient/GetPopLists", ReplyAction="http://cif.speerit.nl/IIsacClient/GetPopListsResponse")]
        System.Threading.Tasks.Task<string[]> GetPopListsAsync(int owner);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BcViewRequest
    {
        
        public BcViewRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BcViewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BcViewResponse", Namespace="http://cif.speerit.nl/", Order=0)]
        public IIsAcService.BcViewResponseBody BcViewResponse1;
        
        public BcViewResponse()
        {
        }
        
        public BcViewResponse(IIsAcService.BcViewResponseBody BcViewResponse1)
        {
            this.BcViewResponse1 = BcViewResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IIsacClientChannel : IIsAcService.IIsacClient, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class IsacClientClient : System.ServiceModel.ClientBase<IIsAcService.IIsacClient>, IIsAcService.IIsacClient
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IsacClientClient() : 
                base(IsacClientClient.GetDefaultBinding(), IsacClientClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IIsacClient.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsacClientClient(EndpointConfiguration endpointConfiguration) : 
                base(IsacClientClient.GetBindingForEndpoint(endpointConfiguration), IsacClientClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsacClientClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IsacClientClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsacClientClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IsacClientClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IsacClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IIsAcService.BcViewResponse> IIsAcService.IIsacClient.BcViewAsync(IIsAcService.BcViewRequest request)
        {
            return base.Channel.BcViewAsync(request);
        }
        
        public System.Threading.Tasks.Task<IIsAcService.BcViewResponse> BcViewAsync()
        {
            IIsAcService.BcViewRequest inValue = new IIsAcService.BcViewRequest();
            return ((IIsAcService.IIsacClient)(this)).BcViewAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<byte[]> BcViewResponseStreamAsync()
        {
            return base.Channel.BcViewResponseStreamAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetPopListsAsync(int owner)
        {
            return base.Channel.GetPopListsAsync(owner);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIsacClient))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIsacClient))
            {
                return new System.ServiceModel.EndpointAddress("http://10.5.1.200:55548/IisAcService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IsacClientClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IIsacClient);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IsacClientClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IIsacClient);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IIsacClient,
        }
    }
}
